# include: package:very_good_analysis/analysis_options.yaml

# analyzer:
#   exclude:
#     - "**/*.g.dart"
#     - "**/*.freezed.dart"
#     - "test/.test_coverage.dart"

# linter:
#   rules:
#     public_member_api_docs: false
#     sort_pub_dependencies: false
    # Engineering Nomenclature Exceptions:
    # We allow non_constant_identifier_names at file level ONLY for electrical physics files
    # via ignore_for_file directives, but we keep the rule enabled globally to catch
    # bad naming in UI/Logic layers.
